apiVersion: v1
kind: Pod
metadata:
  labels:
    app: terminal
  name: terminal
spec:
  # https://github.com/mborne/terminal
  containers:
  - name: terminal
    image: "ghcr.io/mborne/terminal:v0.3.0"
    securityContext:
      capabilities:
        drop:
        - ALL
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    volumeMounts:
      - name: data
        mountPath: /home/debug
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
  volumes:
    - name: data
      emptyDir:
        sizeLimit: 1Gi
  restartPolicy: Never
